name: dia_sin_beber
description: "Aplicación para registrar los progresos de la sobriedad."
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase  
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  # Otros
  table_calendar: ^3.0.9
  intl: 0.20.2
  shared_preferences: ^2.1.2
  cupertino_icons: ^1.0.8

  # Actualización automática
  updatermaster: ^0.0.2

  http: ^1.1.0

  # Información de la app
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icono.png"
  remove_alpha_ios: true
